name: lint-and-test

on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: make install
      - run: make editorconfig
      - run: make lint
      - run: make lint-styles
      - run: make test
